version: "3"
services:
  api:
    container_name: fast-api-concept
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./api:/usr/fastapi-concept/api
    depends_on:
      - db
      - redis-cache
      - mock-api

  mock-api:
    container_name: discounts-api
    build:
      context: .
      dockerfile: mocker-api/Dockerfile.dev
    ports:
      - "5000:5000"

  db:
    image: postgres:14.2-alpine
    container_name: concept-db
    volumes:
      - ./scripts/create-multiple-postgres-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgres-databases.sh
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_MULTIPLE_DATABASES=concept_db,concept_db_test
    ports:
      - "5432:5432"

  redis-cache:
    image: redis:7.0.7-alpine
    container_name: concept-cache
    ports:
      - "6739:6739"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
  

volumes:
  redis-data:
