version: "3"
services:
  api:
    container_name: fast-api-concept
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./api:/usr/api
    depends_on:
      - db
      - redis-cache

  db:
    image: postgres:14.2-alpine
    container_name: concept-db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DATABASE=concept_db
    ports:
      - "5432:5432"

  redis-cache:
    image: redis:7.0.7-alpine
    container_name: concept-cache
    ports:
      - "6739:6739"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
  

volumes:
  db-data:
  redis-data:
