FROM python:3.10
RUN pip3 install uvicorn
COPY .env ./usr/
WORKDIR /usr
COPY ./requirements.txt /usr/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /usr/requirements.txt
COPY ./api /code/api
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]